name: Unzip Uploaded ZIP Files
on: [push, workflow_dispatch]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # Wichtig für Schreibrechte!

      - name: Unzip file and ignore Git metadata
        run: |
          mkdir -p unzipped_files
          # -o: Überschreibt ohne Fragen
          # -x: Schließt .git/* Dateien aus
          unzip -o '*.zip' -d unzipped_files/ -x '*.git/*' '__MACOSX/*'
          
          # Lösche die ZIP-Datei nach dem Entpacken
          rm -f *.zip

          # Entferne eventuelle Git-Metadaten aus dem entpackten Inhalt
          find unzipped_files/ -name '.git' -exec rm -rf {} + || true

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git status
          git commit -m "Automatisch ZIP-Datei entpackt und bereinigt" || echo "Keine Änderungen"
          git push
