name: Unzip and Process Files
on: [push, workflow_dispatch]

permissions:
  contents: write  # Explizite Schreibberechtigung setzen

jobs:
  process_zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Für bessere Git-Historie

      - name: Unzip Files
        run: |
          # Erstelle Zielordner
          mkdir -p unzipped_content
          
          # Entpacke alle ZIPs und ignoriere macOS/Metadaten
          find . -name "*.zip" -exec unzip -o {} -d unzipped_content \; -exec rm {} \;
          
          # Bereinige unerwünschte Dateien
          find unzipped_content -name '.DS_Store' -delete
          find unzipped_content -name '__MACOSX' -exec rm -rf {} +
          find unzipped_content -name '.git' -exec rm -rf {} +

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Nur relevante Dateien hinzufügen
          git add unzipped_content/
          git rm *.zip || true
          
          git commit -m "Automatisch verarbeitet: ZIP entpackt und bereinigt" || echo "Keine Änderungen"
          
          # Authentifizierung mit Token
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:main
