name: Unzip Files to Root
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  unzip_to_root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Unzip to root directory
        run: |
          # 1. Erst entpacken
          unzip -o '*.zip' -x '__MACOSX/*' '.DS_Store'
          
          # 2. Dann bereinigen
          rm -rf __MACOSX || true
          find . -name '.DS_Store' -delete
          
          # 3. ZIP-Datei erst NACH dem Entpacken löschen
          git rm -f *.zip || true
          rm -f *.zip

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "ZIP-Datei entpackt und bereinigt" || echo "Keine Änderungen"
          git push
