name: Unzip Files to Root
on: [push, workflow_dispatch]

permissions:
  contents: write  # Schreibberechtigungen explizit setzen

jobs:
  unzip_to_root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Für vollständige Git-Historie

      - name: Unzip directly to root
        run: |
          # Lösche vorhandene ZIP-Datei (falls sie schon im Repository war)
          git rm -f *.zip || true
          
          # Entpacke alle ZIP-Dateien direkt ins Root-Verzeichnis
          find . -name "*.zip" -exec unzip -o {} \; -exec rm {} \;
          
          # Bereinige macOS-Metadaten und Git-Reste
          find . -name '__MACOSX' -exec rm -rf {} +
          find . -name '.DS_Store' -delete
          find . -name '.git' -type d -exec rm -rf {} +

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "ZIP-Datei direkt ins Root entpackt" || echo "Keine Änderungen"
          git push
