name: Unzip Uploaded ZIP Files
on: [push, workflow_dispatch]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find and unzip ZIP files
        run: |
          mkdir -p unzipped_files
          for zip_file in *.zip; do
            if [ -f "$zip_file" ]; then
              echo "➡ Entpacke $zip_file..."
              unzip "$zip_file" -d "unzipped_files/${zip_file%.zip}"
              rm "$zip_file"
            fi
          done

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automatisch ZIP-Datei entpackt" || echo "Keine Änderungen"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
