name: Unzip Uploaded ZIP Files
on: [push, workflow_dispatch]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      # Schritt 1: Repository auschecken
      - uses: actions/checkout@v4

      # Schritt 2: Alle ZIP-Dateien finden & entpacken
      - name: Find and unzip all ZIP files
        run: |
          # Erstelle einen Ordner für entpackte Dateien
          mkdir -p unzipped_files  

          # Suche alle ZIP-Dateien im Root-Verzeichnis und entpacke sie
          for zip_file in *.zip; do
            if [ -f "$zip_file" ]; then
              echo "➡ Entpacke $zip_file..."
              unzip "$zip_file" -d "unzipped_files/${zip_file%.zip}"
              rm "$zip_file"  # Lösche die ZIP-Datei (optional)
            fi
          done

          # Falls keine ZIP gefunden wurde
          if [ ! -f *.zip ]; then
            echo "ℹ Keine ZIP-Datei gefunden."
          fi

      # Schritt 3: Änderungen committen & pushen
      - name: Commit and push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          commit_message: "Automatisch ZIP-Datei(en) entpackt"
          force: true  # Überschreibt ggf. vorhandene Dateien
